apiVersion: v1
kind: Service
metadata:
  name: tempestd
  namespace: tempestd
spec:
  type: ClusterIP
  selector:
    app: tempestd
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
